import type { Provider } from "@/entities/provider/provider.types";

export const providers: Provider[] = [
  {
    id: "anthropic",
    name: "Anthropic",
    type: "api",
    privacyMax: "public",
    status: "connected",
    enabled: true,
    maskedKey: "sk-ant-******abc1",
  },
  {
    id: "openai",
    name: "OpenAI",
    type: "api",
    privacyMax: "public",
    status: "missing_key",
    enabled: false,
  },
  {
    id: "chutes",
    name: "Chutes",
    type: "bittensor",
    privacyMax: "sensitive",
    status: "connected",
    enabled: true,
    maskedKey: "ch_******92ff",
  },
  {
    id: "targon",
    name: "Targon",
    type: "bittensor",
    privacyMax: "confidential",
    status: "connected",
    enabled: true,
    maskedKey: "tg_******71bc",
  },
  {
    id: "together",
    name: "Together AI",
    type: "api",
    privacyMax: "public",
    status: "missing_key",
    enabled: false,
  },
  {
    id: "fireworks",
    name: "Fireworks",
    type: "api",
    privacyMax: "public",
    status: "missing_key",
    enabled: false,
  },
  {
    id: "groq",
    name: "Groq",
    type: "api",
    privacyMax: "public",
    status: "missing_key",
    enabled: false,
  },
  {
    id: "deepinfra",
    name: "DeepInfra",
    type: "api",
    privacyMax: "sensitive",
    status: "missing_key",
    enabled: false,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    type: "aggregator",
    privacyMax: "public",
    status: "missing_key",
    enabled: false,
  },
];
